name: deploy

on:
  push:
    branches: [ "main" ]

    paths-ignore:
      - ".github/workflows/page.yml"
      - "app/**"

jobs:
  build-and-deploy:
    environment: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check all secrets
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PASS: ${{ secrets.SERVER_PASSWORD }}
          KEY: ${{ secrets.SERVER_SSH_KEY }}

        run: |
          missing=0
          
          [ -n "$HOST" ] || { echo "SERVER_HOST missing"; missing=1; }
          [ -n "$USER" ] || { echo "SERVER_USER missing"; missing=1; }
          
          if [ -z "$PASS" ] && [ -z "$KEY" ]; then
            echo "need SERVER_PASSWORD or SERVER_SSH_KEY"
            missing=1
          fi
          
          if [ "$missing" -eq 1 ]; then
            exit 1
          fi
          
          echo "✔ all required secrets exist"

      # backend
      - name: Build ktor
        run: ./gradlew :server:shadowJar

      - name: Upload jar to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "server/build/libs/mikunpic-0.2.1.jar"
          target: "~/.config/mikunpic/temp/"
          strip_components: 3

      - name: Upload install script
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "server/deployment/install-user.sh"
          target: "~/.config/mikunpic/temp/"
          strip_components: 2

      - name: Upload user service template
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "server/deployment/mikunpic-user.service"
          target: "~/.config/mikunpic/temp/"
          strip_components: 2

      - name: Restart service
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            SOURCE_JAR="$HOME/.config/mikunpic/temp/mikunpic-0.2.1.jar" \
              bash "$HOME/.config/mikunpic/temp/install-user.sh"
